### ISSUE TITLE
Villagers not moving around

### ISSUE THREAD

**Issue by Nexusdog** [Orange1861/Improved-Villagers#12]
Observed behaviour - villagers which spawn in villages are rooted to the spot. 
Children move, but movement is jerky. 
Villagers suddenly appear when holding emeralds
Villagers mate then disappear (go back to their original position?)
When planting crops, there is a delay between planting several crops. Also jerky movement observed

**Comment by Orange1861** [comment]
Post the console logs and does this happen to all villagers everywhere or certain villages?

**Comment by Nexusdog** [comment]
From what I've observed, it's all villagers

https://pastebin.com/9ZhPMN0i

**Comment by Orange1861** [comment]
Alright, this looks like it is not just improved villagers instead it appears to be other mods interfering with each other and causing major issues according to the log.

Backup your world and then try playing the backup world with only improved villagers.
If the issues continue:
Tell me when the issue starts (like at the start or later)
Post the new console logs.

I'd recommend reviewing the mods that you have as they seem to be causing issues and flower pots and some sheep can't be loaded loaded by mc according to thee log.

**Comment by Nexusdog** [comment]
Okay, made a duplicate world with only Mo'villages & Journeymap mods.

Villagers definitely rooted to spot in their spawn positions, interacting with them makes no change to behaviour.

https://pastebin.com/qbm4iP0Y

**Comment by Orange1861** [comment]
Try without Mo' Villages and then send me the save file if possible, I'll try testing them now.

**Comment by Orange1861** [comment]
Hmmm, while they seem to work, they don't have the normal mc urge to wander, I'll fix this now.

**Comment by Orange1861** [comment]
Alright, I have fixed the lack of villager wandering in beta 4, if you have any other issues with their AI, post a new issue after I release beta 4.

**Comment by Nexusdog** [comment]
Okay, removed Mo'villages - success, villagers now happily wandering around.
Only two classes spawning; priests & blacksmiths

Deleted previous config to avoid anomalous results

Log https://pastebin.com/A6mNADg0

**Comment by Orange1861** [comment]
@Nexusdog 

Create a new issue for that.
As well, I had a librarian spawn in my tests (I only tested and looked at three) so I'm not sure if that is happening. Try Mo'Villages now since beta 4 should have fixed the wandering issue.

**Comment by Orange1861** [comment]
@Nexusdog 

Also, thank you again for posting issues here, it is making the mod better since I lack time for complete testing.

**Comment by Nexusdog** [comment]
Okay, so I tested again with my full modded game and made a duplicate, using beta 4.

Some villagers are moving around, some still appear to be rooted to the spot. 
Majority of villagers are alchemists & arborists.

Moved out of spawn, new chunks, new villages
Villager behaviour; initially rooted to spot. Those spawning on farms start moving than others outside of huts or on dirt, sand, grassy blocks etc. Villagers in buildings seem the last to move.
Majority of villagers primarily alchemists

https://i.gyazo.com/eee0da3f2d23065b469a9572a398686b.png

16 Villagers
5 Alchemists
3 Armorers
1 Farmer
1 Shady Merchant
1 Arborist
2 Undertakers
2 Librarians
1 Jam Guy

*Changed config - set enable cities to False

**Comment by Nexusdog** [comment]
Forgot to add after I removed the fences, the villagers began moving around freely.

**Comment by Orange1861** [comment]
This seems more like a lag issue or is it that the villagers only start after a long time (more than 5 mins).

**Comment by Nexusdog** [comment]
Not sure if it's lag, it's just that they seem to need a bit of time thinking about what they're going to do. Once they remember, they'll happily do their thing.

Incidentally, you might want to tweak the threshold where villagers are attracted to emeralds - is it around 12-16 blocks away at present? They were coming at me at a run from quite far away when I held an emerald.

**Comment by Orange1861** [comment]
@Nexusdog So basically the villagers take some initial time before they wander and then they wander freely for the rest of the game? Or do reloads make villagers prevent villagers from wandering for a while?

I'll turn the villager emerald following down if possible.

**Comment by Orange1861** [comment]
Actually wandering and emerald following are both vanilla systems that I have tied into the IvVillager so it may be a while before I get around to making those minor fixes.

**Comment by Nexusdog** [comment]
Villagers are good now, think you've nailed it apart from the balance of alchemists :-)

**Comment by Orange1861** [comment]
BTW, what are alchemists? You keep talking about them but idk what they are.

**Comment by Nexusdog** [comment]
Ah. Okay, various mods add new villager classes;
Jam Guy - Actually Additions
Alchemist - Extra Utilities 2
Undertakers - Gravestone 
Arborists - Forestry
Shady Merchant - Extra Utilties 2

I've just gone through the configs to see how it affects the villager spawn rates

Also, the inclusion of cities in your config & issues with Mo'Villages - are you planning on taking over where it left off? That'd be great if it were the case, I love my villages! :-)

**Comment by Orange1861** [comment]
Yes, I'm planning on working on villages to improve them and reduce issues with other mods. Do you have any other suggestions for villages?

**Comment by Nexusdog** [comment]
There's a few other mods which add structures; Ruins, Recurrent Complex, DungeonDQ, Mine Colonies, Minecraft Comes Alive, Abyssalcraft, Lost Cities, etc. They all have something unique about them so it's finding a place within them them without duplicating what they've done - or, do it better than them.

I like Recurrent Complex, has some good buildings but not enough to give villages that same generic feeling. I do like the pirate ships though and the unique skeleton crews.  

Ruins wasn't bad, nice to find interesting things in the world but it didn't add anything to villages

DungeonDQ... some amazing buildings, over 90 iirc, but I can't get it to run, same goes for Lost Cities and my system has a good spec. I haven't paid much attention to DungeonsDQ as I can't run it so no idea on specifics. 

I like the ideas behind Mine Colonies and Minecraft Comes Alive, having interaction beyond trading with villagers is really nice idea - that would be the one idea I'd push for. Witchery included walled towns & cities complete with guards - that would be another idea to go for since Witchery seems dead. I liked the walled villages & guards but nothing else from that mod. Mine Colonies was having real problems recently, became really buggy so I stopped following it, be interesting to see how it's coming along and what it's doing.

Abyssalcraft is a Lovecraftian themed mod with structures and new mobs - I haven't checked it out enough yet to know much about it but it's not bad, just not geared towards the modding villages idea.

Then there are the schematic building mods. I like the idea of them but I can't be arsed to fiddle around with the details tbh. Guess I'm lazy in my old age. :-)

So, what do I think so far... Walled cities & villages with guards from Witchery. Advanced interaction with villagers and new villager professions from Mine Colonies/Minecraft Comes Alive. Great buildings from Recurrent Complex (and DungeonDQ from what I've seen). Great theme from Abyssalcraft.

Also worth mentioning is Carpenter's blocks and Architecturecraft and Chisel for adding new shapes and new textures. Buildings, structures, dungeons desperately need new shaped blocks, new textures and that's the other big thing missing in Minecraft. That and flying craft.

How about you, what's your thoughts on villages and what I've said?

**Comment by Nexusdog** [comment]
Check out the Muon mod for ideas as well! Oh, and Malissi's Doors.

**Comment by Orange1861** [comment]
Well, most of those requires an experienced modder who has better skills than I. In future I'll may push for a large update that includes one of those, but I meant in terms of smaller minor features.

**Comment by Nexusdog** [comment]
Okay, short answer would be Walled villages & guards if possible. Maybe a unique building as your signature.
